APP = "jzero"
Key = "jzero.rpc"
ListenOn = "0.0.0.0:8000"
Mode = "dev"
Name = "jzero.rpc"

[Jzero]
ListenOnUnixSocket = "./jzero.sock"

[Log]
  ServiceName = "jzero"
  Level = "info"
  Mode = "file"
  encoding = "plain"
  KeepDays = 30
  MaxBackups = 7
  MaxSize = 50
  Rotation = "size"

[DevServer]
  Enabled = true

[Gateway]
  Name = "jzero.gw"
  Port = 8001
  MaxConns = 100

  [[Gateway.Upstreams]]
    Name = "jzero.gw"
    ProtoSets = [".protosets/credential.pb", ".protosets/machine.pb"]

    [Gateway.Upstreams.Grpc]
      Endpoints = ["0.0.0.0:8000"]
