APP = "jzero"
Key = "jzero.rpc"
ListenOn = "0.0.0.0:8000"
Mode = "dev"
Name = "jzero.rpc"

[DevServer]
  Enabled = true

[Gateway]
  MaxConns = 100
  Name = "jzero.gw"
  Port = 8001

  [[Gateway.Upstreams]]
    Name = "jzero.gw"
    ProtoSets = [".protosets/credential.pb", ".protosets/machine.pb"]

    [Gateway.Upstreams.Grpc]
      Endpoints = ["0.0.0.0:8000"]

[Jzero]
  ListenOnUnixSocket = "./jzero.sock"

  [Jzero.Mysql]
    Address = "127.0.0.1:33060"
    Database = "jzero"
    Password = "123456"
    Username = "root"

[Log]
  ServiceName = "jzero"
  KeepDays = 30
  Level = "info"
  MaxBackups = 7
  MaxSize = 50 # 50MB
  Mode = "file"
  Rotation = "size"
  encoding = "plain"
