APP = "jzero"
Key = "jzero.rpc"
ListenOn = "0.0.0.0:8000"
Mode = "dev"
Name = "jzero.rpc"

[Jzero]
ListenOnUnixSocket = "./jzero.sock"
GrpcMaxConns = 100

[Log]
  ServiceName = "jzero"
  Mode = "console"
  encoding = "plain"

[DevServer]
  Enabled = true

[Gateway]
  Name = "jzero.gw"
  Port = 8001
  MaxConns = 100

  [[Gateway.Upstreams]]
    Name = "jzero.gw"
    ProtoSets = [".protosets/credential.pb", ".protosets/machine.pb"]

    [Gateway.Upstreams.Grpc]
      Endpoints = ["0.0.0.0:8000"]
