version: '3'
services:
  jzero:
    image: jaronnie/jzero:latest
    ports:
      - "8001:8001"
      - "8002:8002"
    volumes:
      - './config.toml:/app/config.toml'
    environment:
      - Jzero_Mysql_Address=jzero_mysql:3306
      - Jaeger_endpoint=http://jzero_jaeger:14268/api/traces
    command:
      - server
    depends_on:
      - jzero_mysql
    restart: always
  jzero_mysql:
    image: "mysql:5.7"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=jzero
    volumes:
      - ./app/desc/sql:/docker-entrypoint-initdb.d
    restart: always
  jzero_jaeger:
    image: jaegertracing/all-in-one:1.6
    ports:
      - "14268:14268"
      - "16686:16686"
