version: "3"

tasks:
  run:
    cmds:
      - go run main.go daemon --config config.toml
  install:
    deps:
      - build
    cmds:
      - cp dist/jzero_{{OS}}_{{ARCH}}_v1/jzero $GOBIN
    silent: true
  fmt:
    cmds:
      - sh scripts/goimports.sh {{ if empty .CLI_ARGS }}all{{ else }}git{{ end }}
    silent: true
  build:
    cmds:
      - goreleaser build --snapshot --single-target --clean
    silent: true
  release:
    cmds:
      - goreleaser release --rm-dist
    silent: true
  httpsdk:
    cmds:
    - ./scripts/httpsdk.sh debug