version: "3"

tasks:
  gencode:
    cmds:
      - sh ./scripts/gencode.sh
  run:
    cmds:
      - go run main.go jzerod --config config/config.toml
  install:
    deps:
      - build
    cmds:
      - cp dist/jzero_{{OS}}_{{ARCH}}_v1/jzero $GOBIN
    silent: true
  fmt:
    cmds:
      - sh scripts/goimports.sh {{ if empty .CLI_ARGS }}all{{ else }}git{{ end }}
    silent: true
  build:
    cmds:
      - goreleaser build --snapshot --single-target --rm-dist
    silent: true
  release:
    cmds:
      - goreleaser release --rm-dist
    silent: true
  httpsdk:
    cmds:
    - ./scripts/httpsdk.sh debug