Name = "jzerod.rpc"
ListenOn = "0.0.0.0:8000"
Key = "jzerod.rpc"
Mode = "dev"

[DevServer]
Enabled = true

[Telemetry]
Name = "jzerod"
Endpoint = "http://192.168.135.21:14268/api/traces"
Sampler = 1.0
Batcher = "jaeger"

[Gateway]
Name = "gateway"
Port = 8001

  [[Gateway.Upstreams]]
  Name = "rpc-server"
  ProtoSets = [ "protosets/credential.pb", "protosets/machine.pb" ]

    [Gateway.Upstreams.Grpc]
    Endpoints = [ "0.0.0.0:8000" ]

[cli]
server = "localhost:8001"